---
title: "Fig 5"
author: "L. Naslund"
date: "2024-03-18"
output: html_document
---

```{r glines C}
# calculate the time to total carbon storage
glines_total_volume <- 52994001 # total volume from the 1921 line in Figure 10 Bountry et al. 2011 

glines_bulk_density <- 2.03e13/1.51e7 #g m-3

glines_c_content <- (302 * 1e9)/2.03e13

glines_total_c <- (glines_total_volume * glines_bulk_density * glines_c_content) 

glines_c_rate <- glines %>% filter(flux_unit == "C", flux == "reservoir burial") %>% pull(mean_area)

# time to max C storage
glines_max_c_yr <- round(glines_total_c/glines_c_rate, digits = 0) * -1

# accumulated C before removal
glines_total_c_actual <- glines %>% filter(flux == "reservoir burial", flux_unit == "C") %>% pull(mean_area)*87 

# c storage lost in eroded C
glines_eroded_mass <- 9.1 * 1e6 * 1e6 * glines_c_content # table 4 Randle et al. 2015

# after removal storage
glines_nep <- glines %>% filter(flux == "NEP", variation == 100, flux_unit == "CO2-eq") %>% pull(mean_area) 

glines_soil_ch4 <- glines %>% filter(flux == "soil CH4 emissions", flux_unit == "CO2-eq") %>% pull(mean_area) 

# burp
glines_exp_ch4 <- glines %>% filter(flux == "exposed sediment CH4", variation == "pore_5", flux_unit == "CO2-eq") %>% pull(mean_area) 

glines_exp_co2 <-  glines %>% filter(flux == "exposed sediment CO2", variation == "5", flux_unit == "CO2-eq") %>% pull(mean_area) 

glines_drawdown <- glines %>% filter(flux == "drawdown ebullition", variation == "10", flux_unit == "CO2-eq") %>% pull(mean_area)

# after removal emissions
glines_tree_ch4 <- glines %>% filter(flux == "tree CH4 emissions", variation == "three meters", flux_unit == "CO2-eq") %>% pull(mean_area)

glines_river_co2 <- glines %>% filter(flux == "river CO2 emissions", flux_unit == "CO2-eq") %>% pull(mean_area)

glines_river_ch4 <- glines %>% filter(flux == "river CH4 emissions", flux_unit == "CO2-eq") %>% pull(mean_area)


# reservoir emissions
glines_emissions <- glines %>% filter(flux == "reservoir emissions", variation == "with degassing", flux_unit == "CO2-eq") %>% pull(mean_area)

glines_pathway_before <- data.frame(yr = seq(0, 87, by = 1)) %>% mutate(storage_rem = yr * glines_c_rate *44/12, 
                                                                        storage_stay = yr * glines_c_rate *44/12, 
                                                                        emissions_rem = yr * glines_emissions, 
                                                                        emissions_stay = yr * glines_emissions)

glines_pathway_after <- data.frame(yr = seq(87, 375, by = 1)) %>% mutate(storage_rem = ((glines_total_c_actual + glines_eroded_mass)* (44/12)) + ((glines_nep + glines_soil_ch4) * (yr-87)), 
                                                                         storage_stay = if_else(yr < glines_max_c_yr, yr * glines_c_rate *44/12, -glines_total_c * (44/12)), 
                                                                         emissions_rem = (glines_emissions * 87) + (glines_exp_ch4 + glines_exp_co2 + glines_drawdown) + ((glines_tree_ch4 + glines_river_ch4 + glines_river_co2) * (yr - 87)), 
                                                                         emissions_stay = yr * glines_emissions)

glines_pathways.plt <- glines_pathway_before %>% bind_rows(glines_pathway_after) %>% 
  mutate(storage_rem = storage_rem * 1e-9, 
         storage_stay = storage_stay * 1e-9, 
         emissions_rem = emissions_rem * 1e-9, 
         emissions_stay = emissions_stay * 1e-9, 
         total_rem = storage_rem + emissions_rem, 
         total_stay = storage_stay + emissions_stay) %>% 
  ggplot()+
  #geom_hline(aes(yintercept = 0), color = "red", linetype = "dotted", linewidth = 1)+
  geom_line(aes(yr, emissions_stay), linetype = "solid", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, storage_stay), linetype = "solid", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, total_stay), linetype = "dashed", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, storage_rem), linetype = "solid", color = "black", linewidth = 1)+
  geom_line(aes(yr, total_rem), linetype = "dashed", color = "black", linewidth = 1)+
  geom_line(aes(yr, emissions_rem), linetype = "solid", color = "black", linewidth = 1)+
  theme_bw()+
  ggtitle("Glines Canyon Dam")+
  labs(x = "Dam age (yr)", y = expression(Carbon~balance~"(Gg"~CO[2]-eq~")"))+
  theme(axis.text = element_text(size = 14, color = "black"), axis.title = element_text(size =16), plot.title = element_text(size=20, hjust = 0.5))
```

```{r}
# calculate the time to total carbon storage
# c content
veazie_lc <- read.csv("../1-input-data/3-gres/veazie_lc.csv") %>% 
  mutate(gres_class = case_when(
    Legend == "Open Water" ~ "Water Bodies", 
    Legend == "Perennial Snow/Ice" ~ "Permanent Snow/Ice",
    Legend == "Developed, Open Space" ~ "Settlements", 
    Legend == "Developed, Low Intensity" ~ "Settlements", 
    Legend == "Developed, Medium Intensity" ~ "Settlements", 
    Legend == "Developed, High Intensity" ~ "Settlements", 
    Legend == "Barren Land" ~ "Bare Areas",
    Legend == "Deciduous Forest" ~ "Forest", 
    Legend == "Evergreen Forest" ~ "Forest", 
    Legend == "Mixed Forest" ~ "Forest", 
    Legend == "Shrub/Scrub" ~ "Grassland/Shrubland", 
    Legend == "Herbaceuous" ~ "Grassland/Shrubland", 
    Legend == "Hay/Pasture" ~ "Croplands", 
    Legend == "Woody Wetlands" ~ "Wetlands", 
    Legend == "Emergent Herbaceuous Wetlands" ~ "Wetlands",
  ))

lc <- veazie_lc %>% group_by(gres_class) %>% summarize(perc = sum(percent) %>% round(1)) 

# sediment c content model
c_content <- read.csv("../1-input-data/6-clow-data/c_content.csv") %>% 
  mutate(LAKE_ORIGIN_renamed = as.factor(LAKE_ORIGIN_renamed)) %>% 
  dplyr::select(sediment_C_pct, SOC_0_5, Wetlands90, log_Wetlands90, Barren30, KFactor, 
                log_WaterBody_Area_m2, log_Lake_Area_m2_EPA, LAKE_ORIGIN_renamed) %>% mutate(wetland_si = log10(Wetlands90 + 1))

c.mod <- lm(sediment_C_pct ~ SOC_0_5 + wetland_si + Barren30 + KFactor + log_Lake_Area_m2_EPA + LAKE_ORIGIN_renamed, data = c_content)

veazie_c_pred <- read.csv("../1-input-data/6-clow-data/veazie_soil.csv") %>% 
  rename("SOC_0_5" = "soc", "KFactor" = "kf") %>% 
  dplyr::select(-kw) %>% # using kf not kw
  mutate(wetland_si = log10(lc %>% filter(gres_class == "Wetlands") %>% pull(perc)/100 + 1), 
         Barren30 = lc %>% filter(gres_class == "Bare Areas") %>% pull(perc)/100, 
         log_Lake_Area_m2_EPA = log10(as.numeric(veazie %>% filter(flux_unit == "CO2-eq", flux == "reservoir burial") %>% pull(area_m2))), 
         LAKE_ORIGIN_renamed = "RESERVOIR")

predict(c.mod, veazie_c_pred, interval = "prediction")

veazie_c_cont <- predict(c.mod, veazie_c_pred, interval = "prediction")[1] * 0.01

# dry bulk density
oc_dbd <- read.csv("../1-input-data/6-clow-data/oc_dbd.csv", header = F) %>% rename("OC" = "V1", "DBD" = "V2")

oc_dbd.mod <- lm(log(DBD)~log(OC), data = oc_dbd)

temp_oc_df <- data.frame(OC = veazie_c_cont * 100)

veazie_dbd <- exp(predict(oc_dbd.mod, temp_oc_df, interval = "prediction")[1]) * 1e6

# total volume: couldn't find storage capacity listed anywhere so had to approximate with dam height * reservoir area
veazie_total_volume <- veazie_area * 10

veazie_total_c <- veazie_total_volume * veazie_dbd * veazie_c_cont 

# years until max storage
veazie_max_c_yr <- veazie_total_c/(veazie %>% filter(flux == "reservoir burial", flux_unit == "C") %>% pull(mean_area))*-1

# actual C burial rate
veazie_c_rate <- veazie %>% filter(flux_unit == "C", flux == "reservoir burial") %>% pull(mean_area)

# accumulated C before removal
veazie_total_c_actual <- veazie %>% filter(flux == "reservoir burial", flux_unit == "C") %>% pull(mean_area)*100 

# c storage lost in eroded C
# chose the middle of the uniform distribution fit for reservoir sediment volume
veazie_eroded_mass <- 7500 * veazie_dbd * veazie_c_cont 

# after removal storage
veazie_nep <- veazie %>% filter(flux == "NEP", variation == 100, flux_unit == "CO2-eq") %>% pull(mean_area) 

veazie_soil_ch4 <- veazie %>% filter(flux == "soil CH4 emissions", flux_unit == "CO2-eq") %>% pull(mean_area) 

# burp
veazie_exp_ch4 <- veazie %>% filter(flux == "exposed sediment CH4", variation == "pore_5", flux_unit == "CO2-eq") %>% pull(mean_area) 

veazie_exp_co2 <-  veazie %>% filter(flux == "exposed sediment CO2", variation == "5", flux_unit == "CO2-eq") %>% pull(mean_area) 

veazie_drawdown <- veazie %>% filter(flux == "drawdown ebullition", variation == "10", flux_unit == "CO2-eq") %>% pull(mean_area)

# after removal emissions
veazie_tree_ch4 <- veazie %>% filter(flux == "tree CH4 emissions", variation == "three meters angio", flux_unit == "CO2-eq") %>% pull(mean_area)

veazie_river_co2 <- veazie %>% filter(flux == "river CO2 emissions", flux_unit == "CO2-eq") %>% pull(mean_area)

veazie_river_ch4 <- veazie %>% filter(flux == "river CH4 emissions", flux_unit == "CO2-eq") %>% pull(mean_area)

# reservoir emissions
veazie_emissions <- veazie %>% filter(flux == "reservoir emissions", flux_unit == "CO2-eq") %>% pull(mean_area)

veazie_pathway_before <- data.frame(yr = seq(0, 100, by = 1)) %>% mutate(storage_rem = yr * veazie_c_rate *44/12, 
                                                                        storage_stay = yr * veazie_c_rate *44/12, 
                                                                        emissions_rem = yr * veazie_emissions, 
                                                                        emissions_stay = yr * veazie_emissions)

veazie_pathway_after <- data.frame(yr = seq(100, 375, by = 1)) %>% mutate(storage_rem = ((veazie_total_c_actual + veazie_eroded_mass)* (44/12)) + ((veazie_nep + veazie_soil_ch4) * (yr-100)), 
                                                                         storage_stay = if_else(yr < veazie_max_c_yr, yr * veazie_c_rate *44/12, -veazie_total_c * (44/12)), 
                                                                         emissions_rem = (veazie_emissions * 100) + (veazie_exp_ch4 + veazie_exp_co2 + veazie_drawdown) + ((veazie_tree_ch4 + veazie_river_ch4 + veazie_river_co2) * (yr - 100)), 
                                                                         emissions_stay = yr * veazie_emissions)

veazie_pathways.plt <- veazie_pathway_before %>% bind_rows(veazie_pathway_after) %>% 
  mutate(storage_rem = storage_rem * 1e-9, 
         storage_stay = storage_stay * 1e-9, 
         emissions_rem = emissions_rem * 1e-9, 
         emissions_stay = emissions_stay * 1e-9, 
         total_rem = storage_rem + emissions_rem, 
         total_stay = storage_stay + emissions_stay) %>% 
  ggplot()+
  #geom_hline(aes(yintercept = 0), color = "red", linetype = "dotted", linewidth = 1)+
  geom_line(aes(yr, emissions_stay), linetype = "solid", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, storage_stay), linetype = "solid", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, total_stay), linetype = "dashed", color = "grey70", linewidth = 1)+
  geom_line(aes(yr, storage_rem), linetype = "solid", color = "black", linewidth = 1)+
  geom_line(aes(yr, total_rem), linetype = "dashed", color = "black", linewidth = 1)+
  geom_line(aes(yr, emissions_rem), linetype = "solid", color = "black", linewidth = 1)+
  theme_bw()+
  ggtitle("Veazie Dam")+
  labs(x = "Dam age (yr)", y = expression(Carbon~balance~"(Gg"~CO[2]-eq~")"))+
  theme(axis.text = element_text(size = 14, color = "black"), axis.title = element_text(size =16), plot.title = element_text(size=20, hjust = 0.5))
```


```{r}
png("../2-output-data/dam_pathways.png", width = 10, height = 5, units = "in", res = 300)
plot_grid(veazie_pathways.plt, glines_pathways.plt)
dev.off()
```
