---
title: "synthesis"
author: "L. Naslund"
date: "2024-01-22"
output: html_document
---

```{r set up}
library(tidyverse)
library(cowplot)

veazie <- read.csv("../2-output-data/veazie_summary_nep.csv") %>% mutate(dam = "Veazie")
glines <- read.csv("../2-output-data/glines_summary_nep.csv") %>% mutate(dam = "Glines Canyon")

both <- veazie %>% bind_rows(glines)

gen_theme <- function(g){
  return(g +  theme_bw()+
  theme(axis.text.x = element_text(size = 16, color = "black"), axis.text.y = element_text(size = 16, color = "black"), axis.title.x = element_blank(), axis.title.y = element_text(size =20), legend.title = element_blank(), legend.text = element_text(size = 16)))
}

veazie_area <- both %>% filter(dam == "Veazie", flux_unit == "CO2-eq", flux == "reservoir burial") %>% pull(area_m2) 
glines_area <- both %>% filter(dam == "Glines Canyon", flux_unit == "CO2-eq", flux == "reservoir burial") %>% pull(area_m2) 
```

# Main text
```{r Fig 2}
before_after_df <- both %>% filter(
  period %in% c("before", "build"),
  flux_unit == "CO2-eq",
  variation %in% c(NA, "with degassing", "100", "three meters", "three meters angio")
) %>%
  mutate(
    flux = case_when(
      flux == "reservoir emissions" ~ "emissions",
      flux == "reservoir burial" ~ "burial",
      flux == "river CO2 emissions" ~ "river CO2",
      flux == "river CH4 emissions" ~ "river CH4",
      flux == "NEP" ~ "NEP",
      flux == "soil CH4 emissions" ~ "soil CH4",
      flux == "tree CH4 emissions" ~ "tree CH4"
    )
  ) %>%
  mutate(flux_fct = as.factor(flux) %>% fct_relevel(
    c(
      "emissions",
      "burial",
      "river CO2",
      "river CH4",
      "NEP",
      "soil CH4",
      "tree CH4"
    )
  )) %>%
  mutate(
    period_fct = case_when(period == "before" ~ "before",
                           period == "build" ~ "after") %>% fct_relevel("before", "after")
  ) %>%
  mutate(
    mean_area_mg = mean_area * 1e-6,
    ci_lwr_area_mg = ci_lwr_area * 1e-6,
    ci_upr_area_mg = ci_upr_area * 1e-6
  )


veazie_before.plt <- gen_theme(before_after_df %>% filter(dam == "Veazie", period == "before") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylim(-1000, 25000)+
  ggtitle("Veazie Before")+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  theme(plot.title = element_text(size=20, hjust = 0.5))

veazie_after.plt <- gen_theme(before_after_df %>% filter(dam == "Veazie", period == "build") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylim(-1000, 25000)+
  ggtitle("Veazie After")+
    scale_x_discrete(labels = c(expression(river~CO[2]), expression(river~CH[4]), "NEP", expression(soil~CH[4]), expression(tree~CH[4])))+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  theme(plot.title = element_text(size=20, hjust = 0.5))

glines_before.plt <- gen_theme(before_after_df %>% filter(dam == "Glines Canyon", period == "before") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylim(-35000, 2500)+
  ggtitle("Glines Canyon Before")+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  theme(plot.title = element_text(size=20, hjust = 0.5))


glines_after.plt <- gen_theme(before_after_df %>% filter(dam == "Glines Canyon", period == "build") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylim(-35000, 2500)+
  ggtitle("Glines Canyon After")+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  scale_x_discrete(labels = c(expression(river~CO[2]), expression(river~CH[4]), "NEP", expression(soil~CH[4]), expression(tree~CH[4])))+
    theme(plot.title = element_text(size=20, hjust = 0.5))

png("../2-output-data/before_after_flux_paper.png", width = 11, height = 9, units = "in", res = 300)
plot_grid(veazie_before.plt, veazie_after.plt, glines_before.plt, glines_after.plt, ncol = 2, rel_widths = c(0.4, 0.6))
dev.off()
```

```{r presentation before}
png("../2-output-data/presentation_veazie_before.png", width = 5, height = 4, units = "in", res = 300)
gen_theme(before_after_df %>% filter(dam == "Veazie", period == "before") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  theme(plot.title = element_text(size=20, hjust = 0.5))
dev.off()

png("../2-output-data/presentation_glines_before.png", width = 5, height = 4, units = "in", res = 300)
gen_theme(before_after_df %>% filter(dam == "Glines Canyon", period == "before") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  theme(plot.title = element_text(size=20, hjust = 0.5))
dev.off()

png("../2-output-data/presentation_glines_after.png", width = 9, height = 4, units = "in", res = 300)
gen_theme(before_after_df %>% filter(dam == "Glines Canyon", period == "build") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  scale_x_discrete(labels = c(expression(river~CO[2]), expression(river~CH[4]), "NEP", expression(soil~CH[4]), expression(tree~CH[4])))+
    theme(plot.title = element_text(size=20, hjust = 0.5))
dev.off()

png("../2-output-data/presentation_veazie_after.png", width = 9, height = 4, units = "in", res = 300)
gen_theme(before_after_df %>% filter(dam == "Veazie", period == "build") %>% 
  ggplot(aes(flux_fct, mean_area_mg))+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_point(aes(), size = 2)+
  geom_errorbar(aes(x = flux_fct, ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), linewidth = 1, width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  scale_x_discrete(labels = c(expression(river~CO[2]), expression(river~CH[4]), "NEP", expression(soil~CH[4]), expression(tree~CH[4])))+
    theme(plot.title = element_text(size=20, hjust = 0.5))
dev.off()
```


```{r Fig 3}
# best case: exposed sediment CO2_0.0833333333333333, exposed sediment CH4_no_pore_0.0833333333333333, drawdown ebullition_0, eroded sediment emissions

# middle case: exposed sediment CO2_5, exposed_sediment CH4_pore_5, drawdown ebullition_10, eroded sediment emissions

# worst case: exposed sediment CO2_30, exposed_sediment CH4_pore_30, drawdown ebullition_100, eroded sediment emissions

#mutate(var = c("1 month of emissions", "5 years of emissions", "30 years of emissions", "1 month of emissions", "5 years of emissions", "30 years of emissions", "0x annual ebullition", "10x annual ebullition", "100x annual ebullition", "none")

veazie_eroded <- veazie %>% filter(flux_unit == "CO2-eq") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 no_pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 no_pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% slice(10)

veazie_scenarios <- veazie %>% filter(flux_unit == "CO2-eq") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 no_pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 no_pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% 
  bind_rows(veazie_eroded) %>% 
  bind_rows(veazie_eroded) %>% 
  mutate(scenario = rep(c("best", "middle", "worst"), 4)) %>% 
  mutate(
    mean_area_mg = mean_area * 1e-6,
    ci_lwr_area_mg = ci_lwr_area * 1e-6,
    ci_upr_area_mg = ci_upr_area * 1e-6
  )

veazie_scen_fig <- gen_theme(ggplot(veazie_scenarios, aes(flux, mean_area_mg, color = scenario))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
  geom_errorbar(aes(ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5) + ylab(expression(Mg~CO[2-eq]))+ scale_color_manual(name = "scenario", values = c( "#155AAE",  "grey40", "#C34237"), labels = c("least", "moderate", "most"))+
    scale_x_discrete(labels = c(expression(atop("drawdown", "ebullition")), expression(atop("eroded sediment", "emissions")), expression(atop("exposed",sediment~CH[4])), expression(atop("exposed",sediment~CO[2]))))) + theme(legend.title = element_text(size = 16))

# summary of veazie burp
veazie_scenarios_summary <- veazie_scenarios %>% group_by(scenario) %>% summarize(net_g = sum(mean_area), net_g_lwr = sum(ci_lwr_area), net_g_upr = sum(ci_upr_area), net_kg = net_g * 0.001, net_mg = net_g * 1e-6, net_mg_lwr = net_g_lwr * 1e-6, net_mg_upr = net_g_upr * 1e-6, net_flux = net_g/veazie_area)

veazie_scenarios_summary_fig <- gen_theme(ggplot(veazie_scenarios_summary, aes(scenario, net_mg, color = scenario))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
    scale_x_discrete(labels = c("least", "moderate", "most"))+
  geom_errorbar(aes(ymin = net_mg_lwr, ymax = net_mg_upr), size = 1, position = position_dodge(width = 0.7), width = 0.5) + ylab(expression(Mg~CO[2-eq]))+ scale_color_manual(name = "scenario", values = c( "#155AAE",  "grey40", "#C34237"), labels = c("least", "moderate", "most")))+ theme(legend.position="none")

glines_eroded <- glines %>% filter(flux_unit == "CO2-eq") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% slice(10)

glines_scenarios <- glines %>% filter(flux_unit == "CO2-eq") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% 
  bind_rows(glines_eroded) %>% 
  bind_rows(glines_eroded) %>% 
  mutate(scenario = rep(c("best", "middle", "worst"), 4)) %>% 
    mutate(
    mean_area_mg = mean_area * 1e-6,
    ci_lwr_area_mg = ci_lwr_area * 1e-6,
    ci_upr_area_mg = ci_upr_area * 1e-6
  )

glines_scen_fig <- gen_theme(ggplot(glines_scenarios, aes(flux, mean_area_mg, color = scenario))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
  geom_errorbar(aes(ymin = ci_lwr_area_mg, ymax = ci_upr_area_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5) + ylab(expression(Mg~CO[2-eq]))+ scale_color_manual(name = "scenario", values = c( "#155AAE",  "grey40", "#C34237"), labels = c("least", "moderate", "most"))+
    scale_x_discrete(labels = c(expression(atop("drawdown", "ebullition")), expression(atop("eroded sediment", "emissions")), expression(atop("exposed",sediment~CH[4])), expression(atop("exposed",sediment~CO[2]))))) + theme(legend.title = element_text(size = 16))

glines_scenarios_summary <- glines_scenarios %>% group_by(scenario) %>% summarize(net_g = sum(mean_area), net_g_lwr = sum(ci_lwr_area), net_g_upr = sum(ci_upr_area), net_kg = net_g * 0.001, net_mg = net_g * 1e-6, net_mg_lwr = net_g_lwr * 1e-6, net_mg_upr = net_g_upr * 1e-6, net_flux = net_g/veazie_area) %>% dplyr::select(scenario, net_mg, net_mg_lwr, net_mg_upr)

glines_scenarios_summary_fig <- gen_theme(ggplot(glines_scenarios_summary, aes(scenario, net_mg, color = scenario))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
    scale_x_discrete(labels = c("least", "moderate", "most"))+
  geom_errorbar(aes(ymin = net_mg_lwr, ymax = net_mg_upr), size = 1, position = position_dodge(width = 0.7), width = 0.5) + ylab(expression(Mg~CO[2-eq]))+ scale_color_manual(name = "scenario", values = c( "#155AAE",  "grey40", "#C34237"), labels = c("least", "moderate", "most")))+ theme(legend.position="none")

options(scipen =3)
png("../2-output-data/burp_scenarios.png", width = 14, height = 9, units = "in", res = 300)
plot_grid(veazie_scen_fig, veazie_scenarios_summary_fig, glines_scen_fig, glines_scenarios_summary_fig, rel_widths = c(0.7, 0.3), ncol = 2, labels = "AUTO", label_size = 20)
dev.off()
```

```{r presentation burp}
png("../2-output-data/presentation_veazie_burp.png", width = 9, height = 5, units = "in", res = 300)
veazie_scen_fig
dev.off()

png("../2-output-data/presentation_glines_burp.png", width = 9, height = 5, units = "in", res = 300)
glines_scen_fig
dev.off()
```


```{r Fig 4}
veazie_before <- veazie %>% filter(period == "before", flux_unit == "CO2-eq") %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr), mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Veazie", period = "before")

glines_before <- glines %>% filter(period == "before", flux_unit == "CO2-eq", variation %in% c(NA, "with degassing")) %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr), mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Glines Canyon", period = "before")

# you are going to have to do area weighted fluxes for the m2
# going to use the integrating NEP over 100 yrs each time
#veazie_after_weighted <- veazie %>% filter(period == "build", flux_unit == "CO2-eq", variation %in% c(NA, "100", "three feet angio")) %>% group_by(area_m2) %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr)) %>% ungroup() %>% mutate(mean_w = mean * (area_m2/1648902), ci_lwr_w = ci_lwr * (area_m2/1648902), ci_upr_w = ci_upr * (area_m2/1648902)) %>% summarize(mean = sum(mean_w), ci_lwr = sum(ci_lwr_w), ci_upr = sum(ci_upr_w))

veazie_after <- veazie %>% filter(period == "build", flux_unit == "CO2-eq", variation %in% c(NA, "100", "three feet angio")) %>% summarize(mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Veazie", period = "after") #%>% bind_cols(veazie_after_weighted)

#glines_after_weighted <- glines %>% filter(period == "build", flux_unit == "CO2-eq", variation %in% c(NA, "100", "three feet angio")) %>% group_by(area_m2) %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr)) %>% ungroup() %>% mutate(mean_w = mean * (area_m2/1510000), ci_lwr_w = ci_lwr * (area_m2/1510000), ci_upr_w = ci_upr * (area_m2/1510000)) %>% summarize(mean = sum(mean_w), ci_lwr = sum(ci_lwr_w), ci_upr = sum(ci_upr_w))

glines_after <- glines %>% filter(period == "build", flux_unit == "CO2-eq", variation %in% c(NA, "100", "three feet angio")) %>% summarize(mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Glines Canyon", period = "after") #%>% bind_cols(glines_after_weighted)

before_after <- bind_rows(veazie_before, glines_before, veazie_after, glines_after) %>% mutate(period = as.factor(period) %>% fct_relevel(c("before", "after"))) %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6)


# png("../2-output-data/veazie_after_presentation.png", width = 6, height = 5, units = "in", res = 300)
# gen_theme(before_after %>% filter(dam == "Veazie") %>% 
#   ggplot(aes(period, mean_area))+
#   geom_point(aes(), size = 2)+
#   geom_errorbar(aes(x = period, ymin = ci_lwr_area, ymax = ci_upr_area), linewidth = 1)+
#   ylab(expression(g~CO[2-eq]~yr^-1)))+
#   geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)
# dev.off()
# 
# png("../2-output-data/glines_after_presentation.png", width = 6, height = 5, units = "in", res = 300)
# gen_theme(before_after %>% filter(dam == "Glines Canyon") %>% 
#   ggplot(aes(period, mean_area))+
#   geom_point(aes(), size = 2)+
#   geom_errorbar(aes(x = period, ymin = ci_lwr_area, ymax = ci_upr_area), linewidth = 1)+
#   ylab(expression(g~CO[2-eq]~yr^-1)))+
#   geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)
# dev.off()

before_after_mf <- gen_theme(before_after %>% 
  ggplot(aes(period, mean_mg))+
  geom_point(aes(), size = 2)+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  geom_errorbar(aes(x = period, ymin = lwr_mg, ymax = upr_mg), linewidth = 1)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  facet_wrap(~dam)+
  theme(strip.text = element_text(size = 16))


png("../2-output-data/fig-4.png", width = 8, height = 5, units = "in", res = 300)
before_after_mf
dev.off()
```

```{r presentation after}
png("../2-output-data/presentation_veazie_after.png", width = 5, height = 4, units = "in", res = 300)
gen_theme(before_after %>% filter(dam == "Veazie") %>% 
  ggplot(aes(period, mean_mg))+
  geom_point(aes(), size = 2)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_errorbar(aes(x = period, ymin = lwr_mg, ymax = upr_mg), linewidth = 1)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))
dev.off()

png("../2-output-data/presentation_glines_after.png", width = 5, height = 4, units = "in", res = 300)
gen_theme(before_after %>% filter(dam == "Glines Canyon") %>% 
  ggplot(aes(period, mean_mg))+
  geom_point(aes(), size = 2)+
  geom_hline(yintercept = 0, linetype = "dashed", color = "red", linewidth = 1)+
  geom_errorbar(aes(x = period, ymin = lwr_mg, ymax = upr_mg), linewidth = 1)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))
dev.off()
```


```{r values}
# before after comparison
before_after %>% dplyr::select(dam:upr_mg)

# emissions before
both %>% filter(flux_unit == "CO2-eq", period == "before") %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6) %>% dplyr::select(dam, flux, variation, mean_mg:upr_mg)

# burp
veazie_scenarios_summary %>% dplyr::select(scenario, net_mg:net_mg_upr)
glines_scenarios_summary

# emissions after
both %>% filter(flux_unit == "CO2-eq", period == "build") %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6) %>% dplyr::select(dam, flux, variation, mean_mg:upr_mg)
```



# Supplemental

```{r supplemental values}
veazie_before_c <- veazie %>% filter(period == "before", flux_unit == "C") %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr), mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Veazie", period = "before")

glines_before_c <- glines %>% filter(period == "before", flux_unit == "C", variation %in% c(NA, "with degassing")) %>% summarize(mean = sum(mean), ci_lwr = sum(ci_lwr), ci_upr = sum(ci_upr), mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Glines Canyon", period = "before")

veazie_after_c <- veazie %>% filter(period == "build", flux_unit == "C", variation %in% c(NA, "100", "three feet angio")) %>% summarize(mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Veazie", period = "after") #%>% bind_cols(veazie_after_weighted)

glines_after_c <- glines %>% filter(period == "build", flux_unit == "C", variation %in% c(NA, "100", "three feet angio")) %>% summarize(mean_area = sum(mean_area), ci_lwr_area = sum(ci_lwr_area), ci_upr_area = sum(ci_upr_area)) %>% mutate(dam = "Glines Canyon", period = "after") #%>% bind_cols(glines_after_weighted)

before_after_c <- bind_rows(veazie_before_c, glines_before_c, veazie_after_c, glines_after_c) %>% mutate(period = as.factor(period) %>% fct_relevel(c("before", "after"))) %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6)

# before after comparison
before_after_c %>% dplyr::select(dam:upr_mg)

# emissions before
both %>% filter(flux_unit == "C", period == "before") %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6) %>% dplyr::select(dam, flux, variation, mean_mg:upr_mg)

# emissions after
both %>% filter(flux_unit == "C", period == "build") %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6) %>% dplyr::select(dam, flux, variation, mean_mg:upr_mg)
```


```{r Fig S1}
png("../2-output-data/fig-s1.png", width = 8, height = 5, units = "in", res = 300)
gen_theme(both %>% filter(flux_unit == "CO2-eq", flux == "reservoir emissions") %>% mutate(var = if_else(is.na(variation), "without degassing", variation)) %>% 
  ggplot()+
  geom_point(aes(dam, mean), size = 2)+
  geom_errorbar(aes(x = dam, ymin = ci_lwr, ymax = ci_upr, linetype = var), linewidth = 1, width = 0.5)+
     ylab(expression(g~CO[2-eq]~m^-2~yr^-1))+
    scale_linetype_manual(values = c("dashed", "solid")))
dev.off()
```

```{r Fig S2}
veazie_burp_pub <- veazie %>% filter(period == "burp", flux_unit == "CO2-eq") %>% mutate(var = c("1 month", "1 year", "5 years", "10 years", "30 years", "DNI", "1 month - PE", "1 year - PE", "5 years - PE", "10 years - PE", "30 years - PE", "DNI","1 month + PE", "1 year + PE", "5 years + PE", "10 years + PE", "30 years + PE", "DNI", "x0", "x5", "x10", "x25", "x100", "NA")) %>% filter(var != "DNI") %>% mutate(var_fct = as.factor(var) %>%  fct_relevel(c("1 month", "1 year", "5 years", "10 years", "30 years", "1 month - PE", "1 year - PE", "5 years - PE", "10 years - PE", "30 years - PE", "1 month + PE", "1 year + PE", "5 years + PE", "10 years + PE", "30 years + PE", "x0", "x5", "x10", "x25", "x100", "NA"))) %>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6)

glines_burp_pub <- glines %>% filter(period == "burp", flux_unit == "CO2-eq") %>% mutate(var = c("1 month", "1 year", "5 years", "10 years", "30 years", "DNI", "1 month - PE", "1 year - PE", "5 years - PE", "10 years - PE", "30 years - PE", "DNI","1 month + PE", "1 year + PE", "5 years + PE", "10 years + PE", "30 years + PE", "DNI", "x0", "x5", "x10", "x25", "x100", "NA")) %>% filter(var != "DNI") %>% mutate(var_fct = as.factor(var) %>%  fct_relevel(c("1 month", "1 year", "5 years", "10 years", "30 years", "1 month - PE", "1 year - PE", "5 years - PE", "10 years - PE", "30 years - PE", "1 month + PE", "1 year + PE", "5 years + PE", "10 years + PE", "30 years + PE", "x0", "x5", "x10", "x25", "x100", "NA")))%>% mutate(mean_mg = mean_area * 1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6)

veazie_burp_var <- gen_theme(ggplot(veazie_burp_pub, aes(var_fct, mean_mg, color = flux))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
  geom_errorbar(aes(ymin = lwr_mg, ymax = upr_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5)+
    ggtitle("Veazie Dam")+
  ylab(expression(Mg~CO[2-eq])))+
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), axis.title.x = element_blank(), plot.title = element_text(size=20, hjust = 0.5))

glines_burp_var <- gen_theme(ggplot(glines_burp_pub, aes(var_fct, mean_mg, color = flux))+
  geom_point(size = 2, position = position_dodge(width = 0.7))+
  geom_errorbar(aes(ymin = lwr_mg, ymax = upr_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5)+
    ggtitle("Glines Canyon Dam")+
  ylab(expression(Mg~CO[2-eq])))+
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), axis.title.x = element_blank(), plot.title = element_text(size=20, hjust = 0.5))

png("../2-output-data/fig-s2.png", width = 10, height = 10, units = "in", res = 300)
plot_grid(veazie_burp_var, glines_burp_var, ncol = 1)
dev.off()
```

```{r Fig S3}
veazie_after_var <- gen_theme(veazie %>% filter(flux_unit == "CO2-eq", period == "build") %>% filter(variation %in% c(NA, 100, "offset by canopy angio", "whole trunk angio", "three meters angio", "offset by canopy gymno", "whole trunk gymno", "three meters gymno")) %>% mutate(mean_mg = mean_area *1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6, flux_var = paste0(flux, variation)) %>% 
  ggplot(aes(flux_var, mean_mg))+
  geom_point(size = 2)+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  ggtitle("Veazie Dam")+
 geom_errorbar(aes(ymin = lwr_mg, ymax = upr_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1))+
  scale_x_discrete(labels = c("NEP", expression(river~CH[4]), expression(river~CO[2]), expression(soil~CH[4]), expression(tree~CH[4]~angio~offset),expression(tree~CH[4]~gymno~offset), expression(tree~CH[4]~angio~3~m), expression(tree~CH[4]~gymno~3~m), expression(tree~CH[4]~angio~whole), expression(tree~CH[4]~gymno~whole))))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), axis.title.x = element_blank(), plot.title = element_text(size=20, hjust = 0.5))


glines_after_var <- gen_theme(glines %>% filter(flux_unit == "CO2-eq", period == "build") %>% filter(variation %in% c(NA, 100, "offset by canopy", "whole trunk", "three meters")) %>% mutate(mean_mg = mean_area *1e-6, lwr_mg = ci_lwr_area * 1e-6, upr_mg = ci_upr_area * 1e-6, flux_var = paste0(flux, variation)) %>% ggplot(aes(flux_var, mean_mg))+
  geom_point(size = 2)+
  geom_hline(yintercept = 0, linetype = "dotted", color = "red", linewidth = 1)+
  ggtitle("Glines Canyon Dam")+
 geom_errorbar(aes(ymin = lwr_mg, ymax = upr_mg), size = 1, position = position_dodge(width = 0.7), width = 0.5)+
  ylab(expression(Mg~CO[2-eq]~yr^-1)))+
  scale_x_discrete(labels = c("NEP", expression(river~CH[4]), expression(river~CO[2]), expression(soil~CH[4]), expression(tree~CH[4]~angio~offset), expression(tree~CH[4]~angio~3~m), expression(tree~CH[4]~angio~whole)))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), axis.title.x = element_blank(), plot.title = element_text(size=20, hjust = 0.5))

png("../2-output-data/fig-s3.png", width = 10, height = 10, units = "in", res = 300)
plot_grid(veazie_after_var, glines_after_var, ncol = 1)
dev.off()
```

```{r glines burp scenarios C}
glines_eroded_gC <- glines %>% filter(flux_unit == "C") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% slice(10)

glines_scenarios_gC <- glines %>% filter(flux_unit == "C") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% 
  bind_rows(glines_eroded_gC) %>% 
  bind_rows(glines_eroded_gC) %>% 
  mutate(scenario = rep(c("best", "middle", "worst"), 4))


glines_scenarios_summary_gC <- glines_scenarios_gC %>% group_by(scenario) %>% summarize(net_g = sum(mean_area), net_g_lwr = sum(ci_lwr_area), net_g_upr = sum(ci_upr_area), net_kg = net_g * 0.001, net_mg = net_g * 1e-6, net_mg_lwr = net_g_lwr * 1e-6, net_mg_upr = net_g_upr * 1e-6, net_flux = net_g/veazie_area) %>% dplyr::select(scenario, net_mg, net_mg_lwr, net_mg_upr)

veazie_eroded_gC <- veazie %>% filter(flux_unit == "C") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 no_pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 no_pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% slice(10)

veazie_scenarios_gC <- veazie %>% filter(flux_unit == "C") %>% mutate(flux_var = paste(flux, variation)) %>% filter(flux_var %in% c("exposed sediment CO2 0.0833333333333333", "exposed sediment CH4 no_pore_0.0833333333333333", "drawdown ebullition 0", "exposed sediment CO2 5", "exposed sediment CH4 no_pore_5", "drawdown ebullition 10",  "exposed sediment CO2 30", "exposed sediment CH4 no_pore_30", "drawdown ebullition 100", "eroded sediment emissions NA")) %>% dplyr::select(flux, variation, mean_area, ci_lwr_area, ci_upr_area) %>% 
  bind_rows(veazie_eroded_gC) %>% 
  bind_rows(veazie_eroded_gC) %>% 
  mutate(scenario = rep(c("best", "middle", "worst"), 4))

veazie_scenarios_summary_gC <- veazie_scenarios_gC %>% group_by(scenario) %>% summarize(net_g = sum(mean_area), net_g_lwr = sum(ci_lwr_area), net_g_upr = sum(ci_upr_area), net_kg = net_g * 0.001, net_mg = net_g * 1e-6, net_mg_lwr = net_g_lwr * 1e-6, net_mg_upr = net_g_upr * 1e-6, net_flux = net_g/veazie_area) %>% dplyr::select(scenario, net_mg, net_mg_lwr, net_mg_upr)

veazie_scenarios_summary_gC
glines_scenarios_summary_gC
```

```{r Fig S4}
other_dams <- read_csv("../1-input-data/9-american-rivers-data/ARDamRemovalList_Figshare_Feb2024.csv")

# Veazie 10 m tall 253 m wide
# Glines 64 m tall 46 m wide

other_dams %>% nrow()

other_dams %>% filter(str_detect(Dam_Height_ft,"[^0-9\\.]")==FALSE) %>% nrow()
other_dams %>% filter(str_detect(Dam_Length_ft,"[^0-9\\.]")==FALSE) %>% nrow()

# shorter than Glines
other_dams %>% filter(str_detect(Dam_Height_ft,"[^0-9\\.]")==FALSE) %>% filter(!(Dam_Name %in% c("Veazie Dam", "Glines Canyon Dam"))) %>% mutate(dam_height_m = as.numeric(Dam_Height_ft)*0.3048) %>% filter(dam_height_m < 64) %>% nrow()

# shorter than Veazie
other_dams %>% filter(str_detect(Dam_Height_ft,"[^0-9\\.]")==FALSE) %>% filter(!(Dam_Name %in% c("Veazie Dam", "Glines Canyon Dam"))) %>% mutate(dam_height_m = as.numeric(Dam_Height_ft)*0.3048) %>% filter(dam_height_m < 10) %>% nrow()

# less wide than Veazie
other_dams %>% filter(str_detect(Dam_Length_ft,"[^0-9\\.]")==FALSE) %>% filter(!(Dam_Name %in% c("Veazie Dam", "Glines Canyon Dam"))) %>% mutate(dam_length_m = as.numeric(Dam_Length_ft)*0.3048) %>% filter(dam_length_m < 253) %>% nrow()

# less wide than glines
other_dams %>% filter(str_detect(Dam_Length_ft,"[^0-9\\.]")==FALSE) %>% filter(!(Dam_Name %in% c("Veazie Dam", "Glines Canyon Dam"))) %>% mutate(dam_length_m = as.numeric(Dam_Length_ft)*0.3048) %>% filter(dam_length_m < 46) %>% nrow()

# Veazie blue, Elwha red

dam_height <- other_dams %>% filter(str_detect(Dam_Height_ft,"[^0-9\\.]")==FALSE) %>% mutate(dam_height_m = as.numeric(Dam_Height_ft)*0.3048)%>% ggplot(aes(dam_height_m)) + geom_histogram(binwidth = 2) + geom_vline(xintercept = 10, color = "blue", linewidth = 1, linetype = "dashed") + geom_vline(xintercept = 64, color = "red", linewidth = 1, linetype = "dashed")+
  xlab("dam height (m)")+theme_bw()

dam_length <- other_dams %>% filter(str_detect(Dam_Length_ft,"[^0-9\\.]")==FALSE)%>% mutate(dam_length_m = as.numeric(Dam_Length_ft)*0.3048) %>% ggplot(aes(dam_length_m)) + geom_histogram(binwidth = 50) + geom_vline(xintercept = 253, color = "blue", linewidth = 1, linetype = "dashed") + geom_vline(xintercept = 46, color = "red", linewidth = 1, linetype = "dashed")+
  xlab("dam length (m)")+theme_bw()

dam_age <- other_dams %>% filter(str_detect(Year_Built, "[^0-9]")==FALSE & str_detect(Year_Removed, "[^0-9]")==FALSE) %>% mutate(age = as.numeric(Year_Removed) - as.numeric(Year_Built)) %>% ggplot(aes(age)) + geom_histogram(binwidth = 10) + geom_vline(xintercept = 100, color = "blue", linewidth = 1, linetype = "dashed") + geom_vline(xintercept = 87, color = "red", linewidth = 1, linetype = "dashed")+theme_bw()

png("../2-output-data/figure-s4.png", width = 6, height = 8, units = "in", res = 300)
plot_grid(dam_height, dam_length, dam_age, ncol = 1, labels = "AUTO")
dev.off()
```

# Other

```{r most uncertain}
glines %>% filter(flux_unit == "CO2-eq") %>% mutate(rng = ci_upr_area - ci_lwr_area) %>% arrange(desc(rng))
```

```{r flux net locations}
df <- read.csv("../1-input-data/8-besnard-data/besnard_2018.csv") %>% st_as_sf(coords = c("Long", "Lat"), crs = 4326)

mapview(df)
```

```{r veazie river v reservoir emissions}
# output from g-res: emissions in g CO2 eq by pathway
veazie_co2_diff_eq <- 3
veazie_ch4_diff_eq <- 79 * .89
veazie_ch4_eb_eq <- 79 * 0.11
veazie_ch4_degas_eq <- 0
veazie_ch4 <- veazie_ch4_diff_eq + veazie_ch4_eb_eq + veazie_ch4_degas_eq

# output from g-res: net GHG footprint and 95% CI
veazie_net_eq <- 64
veazie_net_2.5_eq <- 55
veazie_net_97.5_eq <- 75

veazie_net_interval <- max(c(veazie_net_97.5_eq-veazie_net_eq, veazie_net_eq - veazie_net_2.5_eq))

veazie_co2_diff_eq_lwr <- veazie_co2_diff_eq - veazie_net_interval*(veazie_co2_diff_eq/res_eq)
veazie_co2_diff_eq_upr <- veazie_co2_diff_eq + veazie_net_interval*(veazie_co2_diff_eq/res_eq)

veazie_ch4_eq_lwr <- veazie_ch4 - veazie_net_interval * (veazie_ch4/res_eq)
veazie_ch4_eq_upr <- veazie_ch4 + veazie_net_interval * (veazie_ch4/res_eq)

veazie_res_emissions <- data.frame(flux = c("reservoir CO2 emissions", "reservoir CH4 emissions"), 
                                   mean = c(veazie_co2_diff_eq, veazie_ch4), 
                                   ci_lwr = c(veazie_co2_diff_eq_lwr, veazie_ch4_eq_lwr), 
                                   ci_upr = c(veazie_co2_diff_eq_upr, veazie_ch4_eq_upr)) %>% 
  mutate(mean_area = mean * veazie_area, 
                                   ci_lwr_area = ci_lwr * veazie_area, 
                                   ci_upr_area = ci_upr * veazie_area, 
                                   dam = "Veazie")
                                   

veazie_riv_res <- veazie %>% filter(flux_unit == "CO2-eq", flux %in% c("river CO2 emissions", "river CH4 emissions")) %>% dplyr::select(-period, -variation, -annual, - flux_unit, -area, -flux_fct, -area_m2) %>% bind_rows(veazie_res_emissions)


veazie_riv_res %>% ggplot(aes(flux, mean_area))+ geom_point(size = 2)+
  geom_errorbar(aes(ymin = ci_lwr_area, ymax = ci_upr_area), size = 1)+
  scale_y_continuous(trans = "log10")
```


```{r methane comparison}
deemer <- readxl::read_excel("../1-input-data/10-deemer-data/Supplementary_Reservoir_GHG_Data_20200105.xls", skip = 1)

head(deemer)
# glines g co2 m2 yr
44 *(1/365)*(1/34)*(12.01/16.04)*1e3
deemer %>% filter(is.na(`mg CH4-C m-2 d-1 Diffusive + Ebullitive`)==FALSE) %>% nrow()

#65 out of 75 have higher CH4 emissions than Glines
deemer %>% filter(is.na(`mg CH4-C m-2 d-1 Diffusive + Ebullitive`)==FALSE) %>% filter(`mg CH4-C m-2 d-1 Diffusive + Ebullitive`>(44 *(1/365)*(1/34)*(12.01/16.04)*1e3)) %>% nrow()
#60 out of 75 have higher CH4 emissions that Veazie
deemer %>% filter(is.na(`mg CH4-C m-2 d-1 Diffusive + Ebullitive`)==FALSE) %>% filter(`mg CH4-C m-2 d-1 Diffusive + Ebullitive`>(79 *(1/365)*(1/34)*(12.01/16.04)*1e3)) %>% nrow()
```
```{r glines river v reservoir emissions}
## output from g-res: emissions in g CO2 eq by pathway
glines_co2_diff_eq <- 36
glines_ch4_diff_eq <- 44 * 0.6
glines_ch4_eb_eq <- 44 * 0.23
glines_ch4_degas_eq <- 44 * 0.17

# calculate emissions in CO2 eq with degassing
glines_degas_eq <- glines_ch4_diff_eq + glines_ch4_eb_eq +glines_ch4_degas_eq + glines_co2_diff_eq
glines_ch4 <- glines_ch4_diff_eq + glines_ch4_eb_eq +glines_ch4_degas_eq

glines_degas_net <- 367
glines_degas_net_2.5 <- 359
glines_degas_net_97.5 <- 377

glines_net_interval <- max(c((glines_degas_net-glines_degas_net_2.5),(glines_degas_net_97.5-glines_degas_net)))

glines_co2_diff_eq_lwr <- glines_co2_diff_eq - glines_net_interval*(glines_co2_diff_eq/glines_degas_eq)
glines_co2_diff_eq_upr <- glines_co2_diff_eq + glines_net_interval*(glines_co2_diff_eq/glines_degas_eq)

glines_ch4_eq_lwr <- glines_ch4 - glines_net_interval * (glines_ch4/glines_degas_eq)
glines_ch4_eq_upr <- glines_ch4 + glines_net_interval * (glines_ch4/glines_degas_eq)

glines_res_emissions <- data.frame(flux = c("reservoir CO2 emissions", "reservoir CH4 emissions"), 
                                   mean = c(glines_co2_diff_eq, glines_ch4), 
                                   ci_lwr = c(glines_co2_diff_eq_lwr, glines_ch4_eq_lwr), 
                                   ci_upr = c(glines_co2_diff_eq_upr, glines_ch4_eq_upr)) %>% 
  mutate(mean_area = mean * glines_area, 
                                   ci_lwr_area = ci_lwr * glines_area, 
                                   ci_upr_area = ci_upr * glines_area, 
                                   dam = "Glines Canyon")
                                   

glines_riv_res <- glines %>% filter(flux_unit == "CO2-eq", flux %in% c("river CO2 emissions", "river CH4 emissions")) %>% dplyr::select(-period, -variation, -annual, - flux_unit, -area, -flux_fct, -area_m2) %>% bind_rows(glines_res_emissions)


glines_riv_res %>% ggplot(aes(flux, mean_area))+ geom_point(size = 2)+
  geom_errorbar(aes(ymin = ci_lwr_area, ymax = ci_upr_area), size = 1)+
  scale_y_continuous(trans = "log10")

glines_riv_res
```


```{r table of all values}
names(both)
options(scipen =99)

flux_table <- both %>% mutate(mean_rd = signif(mean, 3) %>% round(3), ci_lwr_rd = signif(ci_lwr, 3)%>% round(3), ci_upr_rd = signif(ci_upr, 3)%>% round(3), flux_fmt = paste0(mean_rd, " (", ci_lwr_rd, ", ", ci_upr_rd, ")")) %>% mutate(mean_mg = (mean_area * 1e-6) %>% signif(3), ci_lwr_mg = (ci_lwr_area * 1e-6) %>% signif(3), ci_upr_mg = (ci_upr_area * 1e-6) %>% signif(3), mf_fmt = paste0(mean_mg, " (", ci_lwr_mg, ", ", ci_upr_mg, ")")) %>% select(dam, period, flux, variation, flux_unit, flux_fmt, mf_fmt) %>% pivot_wider(names_from = flux_unit, values_from = c(flux_fmt, mf_fmt))

write.csv(flux_table, "../2-output-data/flux-table.csv", row.names = FALSE)

both %>% mutate(mean_rd = mean, ci_lwr_rd = ci_lwr, ci_upr_rd = ci_upr, flux_fmt = paste0(mean_rd, " (", ci_lwr_rd, ", ", ci_upr_rd, ")")) %>% mutate(mean_mg = (mean_area * 1e-6), ci_lwr_mg = (ci_lwr_area * 1e-6), ci_upr_mg = (ci_upr_area * 1e-6), mf_fmt = paste0(mean_mg, " (", ci_lwr_mg, ", ", ci_upr_mg, ")")) %>% select(dam, period, flux, variation, flux_unit, flux_fmt, mf_fmt) %>% pivot_wider(names_from = flux_unit, values_from = c(flux_fmt, mf_fmt))

```


